services:
  spark-notebook:
    build: .
    container_name: "spark-notebook"
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
